name = "MatrixSign"
uuid = "a25fa8c1-e8fe-40fb-8be2-d139e369b1d5"
version = "1.0.0-DEV"
authors = ["AntonOresten <antonoresten@gmail.com> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ChainRulesCore = "1"
LinearAlgebra = "1"
julia = "1.10"
