name = "MatrixSign"
uuid = "a25fa8c1-e8fe-40fb-8be2-d139e369b1d5"
version = "0.1.0"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
BFloat16s = "ab4f0b2a-ad5b-11e8-123f-65d77653426b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[compat]
BFloat16s = "0.6.0"
ChainRulesCore = "1"
FillArrays = "1.14.0"
LinearAlgebra = "1"
MacroTools = "0.5.16"
NNlib = "0.9.31"
julia = "1.10"
